'use strict';
const $=id=>document.getElementById(id);
const storageKey='salp-browser-desktop-reset-v01';
let z=200,files=[],draftTimer;
function message(id,text){$(id).textContent=text;}
function load(){try{const saved=JSON.parse(localStorage.getItem(storageKey)||'{}');files=Array.isArray(saved.files)?saved.files.filter(f=>typeof f.name==='string'&&typeof f.text==='string'):[];$('editor').value=typeof saved.draft==='string'?saved.draft:'';$('filename').value=typeof saved.filename==='string'?saved.filename:'note.txt';}catch(e){message('storageStatus','保存データを読めませんでした: '+e.message);}}
function persist(){try{localStorage.setItem(storageKey,JSON.stringify({files,draft:$('editor').value,filename:$('filename').value}));return true;}catch(e){message('storageStatus','保存できません: '+e.message);message('editorStatus','ブラウザーに保存できません。書き出すボタンで保存してください。');return false;}}
function openWin(id){const w=$(id);w.style.display='block';w.style.zIndex=++z;w.setAttribute('role','dialog');$('startMenu').style.display='none';if(id==='filesWin')renderFiles();if(id==='terminalWin')$('cmd').focus();}
function closeWin(id){$(id).style.display='none';}
function toggleStart(){const menu=$('startMenu');menu.style.display=menu.style.display==='block'?'none':'block';$('startBtn').setAttribute('aria-expanded',String(menu.style.display==='block'));}
function normalize(raw){let value=raw.trim();if(!value)return null;if(/^https?:\/\//i.test(value)){const u=new URL(value);return u.href;}if(/^[a-z][a-z0-9+.-]*:/i.test(value))throw new Error('http / httpsのURLを入力してください。');if(!/\s/.test(value)&&value.includes('.'))return new URL('https://'+value).href;return 'https://www.google.com/search?q='+encodeURIComponent(value);}
function openExternal(raw){try{const url=normalize(raw);if(!url)return;const link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noopener noreferrer';document.body.append(link);link.click();link.remove();message('browserStatus','サイトを別タブで開きました。');}catch(e){message('browserStatus',e.message);}}
function goUrl(){try{const url=normalize($('url').value);if(url){$('url').value=url;openExternal(url);}}catch(e){message('browserStatus',e.message);}}
function openLinux(){location.href='./linux.html?v=reset01';}
function download(name,text){const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name||'note.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function saveNote(){const name=$('filename').value.trim()||'note.txt';const previous=files.find(f=>f.name===name);const next={name,text:$('editor').value,updated:Date.now()};if(previous)Object.assign(previous,next);else files.push(next);if(persist())message('editorStatus',name+' をこのブラウザーに保存しました。');renderFiles();}
function downloadNote(){download($('filename').value.trim(),$('editor').value);}
function renderFiles(){const list=$('fileList');list.replaceChildren();if(!files.length){list.textContent='保存ファイルはまだありません。読み込むかEditorで作成してください。';return;}for(const file of files){const card=document.createElement('div');card.className='filecard';const title=document.createElement('strong');title.textContent='📄 '+file.name;const meta=document.createElement('small');meta.textContent=new Blob([file.text]).size+' bytes / '+new Date(file.updated).toLocaleString();const actions=document.createElement('div');actions.className='actions';for(const [label,handler]of [['開く',()=>{$('editor').value=file.text;$('filename').value=file.name;persist();openWin('editorWin');message('editorStatus',file.name+' を開きました。');}],['書き出す',()=>download(file.name,file.text)]]){const b=document.createElement('button');b.textContent=label;b.onclick=handler;actions.append(b);}card.append(title,meta,actions);list.append(card);}}
$('importFile').addEventListener('change',async e=>{let count=0;for(const f of e.target.files){if(f.size>1024*1024){message('fileStatus',f.name+': 1MB以下のテキストファイルを選んでください。');continue;}try{const text=await f.text();if(text.includes('\u0000'))throw new Error('テキストファイルを選んでください。');let name=f.name;for(let n=1;files.some(item=>item.name===name);n++)name=f.name+' ('+n+')';files.push({name,text,updated:Date.now()});count++;}catch(error){message('fileStatus',f.name+': '+error.message);}}if(count&&persist())message('fileStatus',count+'件を読み込み、保存しました。');renderFiles();e.target.value='';});
for(const id of ['editor','filename'])$(id).addEventListener('input',()=>{clearTimeout(draftTimer);draftTimer=setTimeout(()=>{if(persist())message('editorStatus','下書きを保存しました。');},350);});
window.addEventListener('pagehide',persist);document.addEventListener('visibilitychange',()=>{if(document.hidden)persist();});
function runCmd(){const cmd=$('cmd').value.trim();$('cmd').value='';let out='';if(cmd==='clear'){$('termOutput').textContent='';return;}if(cmd==='help')out='help, clear, date, echo TEXT, files, editor, browser, linux, about';else if(cmd==='date')out=new Date().toString();else if(cmd.startsWith('echo '))out=cmd.slice(5);else if(cmd==='files')openWin('filesWin');else if(cmd==='editor')openWin('editorWin');else if(cmd==='browser')openWin('browserWin');else if(cmd==='linux')openLinux();else if(cmd==='about')out='ブラウザー用ツールです。実際のLinuxはLinux実行から起動します。';else out=cmd?'未対応のコマンド: '+cmd:'';$('termOutput').textContent+='salp> '+cmd+'\n'+(out?out+'\n':'');$('term').scrollTop=$('term').scrollHeight;}
function tick(){const d=new Date();$('clock').textContent=d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})+' / '+d.toLocaleDateString();}setInterval(tick,1000);tick();
document.querySelectorAll('.window').forEach(w=>w.addEventListener('pointerdown',()=>{w.style.zIndex=++z;}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){const active=Array.from(document.querySelectorAll('.window')).filter(w=>w.style.display==='block').sort((a,b)=>Number(b.style.zIndex)-Number(a.style.zIndex))[0];if(active)closeWin(active.id);$('startMenu').style.display='none';}});
load();renderFiles();
