name: Build salp Linux Browser Image

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Dockerfile
        run: |
          echo "Dockerfile check"
          test -f image/Dockerfile
          cat image/Dockerfile
          echo "Dockerfile found successfully"
